dataset: ImageNet_R
first_split_size: 10
other_split_size: 10
schedule:
- 20
- 0
- 20
schedule_type: coswm
batch_size: 64
optimizer: AdamW
lr: 0.0025
momentum: 0.9
weight_decay: 0
iter_step: 20
model_type: zoo
model_name: vit_pt_imnet
max_task: -1
dataroot: data
workers: 4
validation: False
train_aug: True
rand_split: True